In [9]:
import pandas as pd
import numpy as np

In [10]:
data = pd.read_csv('/Users/bert/Desktop/Projecten/amsterdam_p/Misdrijven/aantalmisdrijven2.csv', sep=';')

In [11]:
data.head(10)

#Give a quick look to my tabel.

,Unnamed: 0,city-part,2015,2016,2017,2018,2019,2015.1,2016.1,2017.1,...,2015.2,2016.2,2017.2,2018.2,2019.2,2015.3,2016.3,2017.3,2018.3,2019.3
0,A,Burgwallen-Oude Zijde,54,67,72,60,102,332,375,403,...,377,429,463,479,468,976,946,1069,1052,910
1,A,Burgwallen-Nieuwe Zijde,235,234,256,202,222,671,683,721,...,881,886,943,682,694,1571,1659,1905,1224,1160
2,A,Grachtengordel-West,11,4,12,10,6,47,56,32,...,56,58,41,35,41,120,125,105,116,99
3,A,Grachtengordel-Zuid,54,37,37,29,28,344,295,302,...,387,324,332,263,237,591,512,504,448,413
4,A,Nieuwmarkt/Lastage,32,30,36,36,42,149,187,177,...,178,211,206,200,233,496,557,555,495,510
5,A,Haarlemmerbuurt,17,18,15,10,9,55,68,71,...,69,85,84,52,63,312,422,360,272,227
6,A,Jordaan,37,23,29,13,20,92,67,96,...,127,89,125,95,94,365,317,308,294,335
7,A,De Weteringschans,29,31,42,26,48,308,294,301,...,331,321,336,245,247,540,467,431,417,356
8,A,Weesperbuurt/Plantage,13,16,6,7,5,42,20,32,...,55,34,38,47,33,135,108,127,131,115
9,A,Oostelijke Eilanden/Kadijken,15,36,15,5,7,48,27,37,...,61,59,51,42,33,153,137,152,151,122

In [12]:
data.columns

Index(['Unnamed: 0', 'city-part', '2015', '2016', '2017', '2018', '2019',
       '2015.1', '2016.1', '2017.1', '2018.1', '2019.1', '2015.2', '2016.2',
       '2017.2', '2018.2', '2019.2', '2015.3', '2016.3', '2017.3', '2018.3',
       '2019.3'],
      dtype='object')

In [13]:
data.columns = ['code', 'city-part', '2015', '2016', '2017', '2018', '2019',
       '2015.1', '2016.1', '2017.1', '2018.1', '2019.1', '2015.2', '2016.2',
       '2017.2', '2018.2', '2019.2', '2015.3', '2016.3', '2017.3', '2018.3',
       '2019.3']

#Here I changed the column name from Unnamed to 'Code'

data.head(15)

,code,city-part,2015,2016,2017,2018,2019,2015.1,2016.1,2017.1,...,2015.2,2016.2,2017.2,2018.2,2019.2,2015.3,2016.3,2017.3,2018.3,2019.3
0,A,Burgwallen-Oude Zijde,54,67,72,60,102,332,375,403,...,377,429,463,479,468,976,946,1069,1052,910
1,A,Burgwallen-Nieuwe Zijde,235,234,256,202,222,671,683,721,...,881,886,943,682,694,1571,1659,1905,1224,1160
2,A,Grachtengordel-West,11,4,12,10,6,47,56,32,...,56,58,41,35,41,120,125,105,116,99
3,A,Grachtengordel-Zuid,54,37,37,29,28,344,295,302,...,387,324,332,263,237,591,512,504,448,413
4,A,Nieuwmarkt/Lastage,32,30,36,36,42,149,187,177,...,178,211,206,200,233,496,557,555,495,510
5,A,Haarlemmerbuurt,17,18,15,10,9,55,68,71,...,69,85,84,52,63,312,422,360,272,227
6,A,Jordaan,37,23,29,13,20,92,67,96,...,127,89,125,95,94,365,317,308,294,335
7,A,De Weteringschans,29,31,42,26,48,308,294,301,...,331,321,336,245,247,540,467,431,417,356
8,A,Weesperbuurt/Plantage,13,16,6,7,5,42,20,32,...,55,34,38,47,33,135,108,127,131,115
9,A,Oostelijke Eilanden/Kadijken,15,36,15,5,7,48,27,37,...,61,59,51,42,33,153,137,152,151,122
10,B10,Westelijk Havengebied,18,11,24,6,8,29,54,53,...,47,64,77,38,55,118,188,135,90,96
11,E12,Houthavens,0,1,0,0,2,1,0,0,...,1,1,0,1,4,5,7,5,8,13
12,E13,Spaarndammer- en Zeeheldenbuurt,18,11,14,11,14,59,55,58,...,75,66,67,85,77,203,226,203,297,215
13,E14,Staatsliedenbuurt,11,8,10,13,21,49,34,31,...,58,42,41,38,54,189,147,138,129,120
14,E15,Centrale Markt,10,12,11,4,13,18,25,13,...,28,37,22,18,30,73,58,62,63,68

In [14]:
data

,code,city-part,2015,2016,2017,2018,2019,2015.1,2016.1,2017.1,...,2015.2,2016.2,2017.2,2018.2,2019.2,2015.3,2016.3,2017.3,2018.3,2019.3
0,A,Burgwallen-Oude Zijde,54,67,72,60,102,332,375,403,...,377,429,463,479,468,976,946,1069,1052,910
1,A,Burgwallen-Nieuwe Zijde,235,234,256,202,222,671,683,721,...,881,886,943,682,694,1571,1659,1905,1224,1160
2,A,Grachtengordel-West,11,4,12,10,6,47,56,32,...,56,58,41,35,41,120,125,105,116,99
3,A,Grachtengordel-Zuid,54,37,37,29,28,344,295,302,...,387,324,332,263,237,591,512,504,448,413
4,A,Nieuwmarkt/Lastage,32,30,36,36,42,149,187,177,...,178,211,206,200,233,496,557,555,495,510
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,T96,Holendrecht/Reigersbos,62,90,55,52,31,75,76,79,...,133,152,122,94,89,352,321,219,256,208
97,T97,Gein,24,27,20,11,12,45,32,25,...,66,56,44,30,42,131,126,70,74,54
98,T98,Driemond,4,0,0,1,0,1,2,2,...,5,2,2,5,1,2,7,5,3,7
99,NaN,onbekend,4,3,0,1,0,42,24,30,...,46,26,31,35,35,136,145,139,138,137
100,NaN,totaal,2450,2261,1974,1755,2026,6290,5640,5336,...,8460,7628,7077,6164,6588,18816,17525,16142,14683,14664

In [15]:
data['12-24'] = data['2015.2']+data['2016.2']+data['2017.2']+data['2018.2']+data['2019.2']

data['25+'] = data['2015.3']+data['2016.3']+data['2017.3']+data['2018.3']+data['2019.3']

In [16]:
data.columns

Index(['code', 'city-part', '2015', '2016', '2017', '2018', '2019', '2015.1',
       '2016.1', '2017.1', '2018.1', '2019.1', '2015.2', '2016.2', '2017.2',
       '2018.2', '2019.2', '2015.3', '2016.3', '2017.3', '2018.3', '2019.3',
       '12-24', '25+'],
      dtype='object')

In [17]:
data.head(40)

,code,city-part,2015,2016,2017,2018,2019,2015.1,2016.1,2017.1,...,2017.2,2018.2,2019.2,2015.3,2016.3,2017.3,2018.3,2019.3,12-24,25+
0,A,Burgwallen-Oude Zijde,54,67,72,60,102,332,375,403,...,463,479,468,976,946,1069,1052,910,2216,4953
1,A,Burgwallen-Nieuwe Zijde,235,234,256,202,222,671,683,721,...,943,682,694,1571,1659,1905,1224,1160,4086,7519
2,A,Grachtengordel-West,11,4,12,10,6,47,56,32,...,41,35,41,120,125,105,116,99,231,565
3,A,Grachtengordel-Zuid,54,37,37,29,28,344,295,302,...,332,263,237,591,512,504,448,413,1543,2468
4,A,Nieuwmarkt/Lastage,32,30,36,36,42,149,187,177,...,206,200,233,496,557,555,495,510,1028,2613
5,A,Haarlemmerbuurt,17,18,15,10,9,55,68,71,...,84,52,63,312,422,360,272,227,353,1593
6,A,Jordaan,37,23,29,13,20,92,67,96,...,125,95,94,365,317,308,294,335,530,1619
7,A,De Weteringschans,29,31,42,26,48,308,294,301,...,336,245,247,540,467,431,417,356,1480,2211
8,A,Weesperbuurt/Plantage,13,16,6,7,5,42,20,32,...,38,47,33,135,108,127,131,115,207,616
9,A,Oostelijke Eilanden/Kadijken,15,36,15,5,7,48,27,37,...,51,42,33,153,137,152,151,122,246,715
10,B10,Westelijk Havengebied,18,11,24,6,8,29,54,53,...,77,38,55,118,188,135,90,96,281,627
11,E12,Houthavens,0,1,0,0,2,1,0,0,...,0,1,4,5,7,5,8,13,7,38
12,E13,Spaarndammer- en Zeeheldenbuurt,18,11,14,11,14,59,55,58,...,67,85,77,203,226,203,297,215,370,1144
13,E14,Staatsliedenbuurt,11,8,10,13,21,49,34,31,...,41,38,54,189,147,138,129,120,233,723
14,E15,Centrale Markt,10,12,11,4,13,18,25,13,...,22,18,30,73,58,62,63,68,135,324
15,E16,Frederik Hendrikbuurt,17,12,11,6,8,38,16,17,...,27,21,23,102,93,94,93,95,153,477
16,E17,Da Costabuurt,9,12,6,8,8,44,42,21,...,26,23,30,170,152,110,68,112,181,612
17,E18,Kinkerbuurt,6,6,7,3,14,20,28,20,...,23,12,22,108,96,49,51,60,116,364
18,E19,Van Lennepbuurt,11,20,10,8,8,49,48,23,...,30,28,32,137,158,98,84,112,215,589
19,E20,Helmersbuurt,12,7,0,3,6,63,28,19,...,19,26,32,137,108,77,50,49,185,421
20,E21,Overtoomse Sluis,8,2,2,8,8,20,16,10,...,12,24,17,72,63,54,42,60,99,291
21,E22,Vondelbuurt,7,5,3,2,6,77,48,40,...,43,50,59,169,102,74,86,105,285,536
22,E36,Sloterdijk,15,4,1,7,6,33,26,20,...,21,22,34,89,90,121,67,96,155,463
23,E37,Landlust,26,42,37,38,31,90,89,56,...,89,91,85,361,321,261,200,200,503,1343
24,E38,Erasmuspark,10,7,14,4,8,26,21,21,...,35,12,21,84,59,51,48,48,131,290
25,E39,De Kolenkit,11,7,12,4,8,52,39,31,...,43,26,36,115,103,98,65,85,212,466
26,E40,Geuzenbuurt,15,5,11,8,13,30,25,21,...,31,21,28,128,122,112,73,78,153,513
27,E41,Van Galenbuurt,15,7,10,7,5,25,29,40,...,49,38,28,86,88,94,91,49,189,408
28,E42,Hoofdweg e.o.,42,14,14,14,12,38,54,37,...,50,28,45,219,172,126,120,131,268,768
29,E43,Westindische Buurt,4,2,1,2,6,19,17,16,...,17,15,13,58,58,33,32,40,85,221
30,E75,ChassÃ©buurt,15,3,8,6,4,30,24,16,...,24,22,17,70,77,39,41,52,130,279
31,F11,Bedrijventerrein Sloterdijk,5,20,39,13,33,61,57,97,...,132,61,111,169,164,238,194,301,446,1066
32,F76,Slotermeer-Noordoost,39,21,28,17,25,49,38,39,...,66,55,64,243,210,174,145,150,327,922
33,F77,Slotermeer-Zuidwest,62,62,35,47,39,87,65,61,...,93,93,93,263,228,155,161,196,544,1003
34,F78,Geuzenveld,15,20,29,20,14,55,66,29,...,56,63,43,189,194,123,129,111,314,746
35,F79,Eendracht,2,1,2,6,5,9,6,8,...,10,9,11,17,18,16,12,16,48,79
36,F80,Lutkemeer/Ookmeer,1,10,0,3,5,8,14,14,...,14,27,19,32,25,26,40,50,89,173
37,F81,Osdorp-Oost,78,41,51,29,55,131,100,86,...,134,101,133,360,322,290,236,271,709,1479
38,F82,Osdorp-Midden,19,15,15,17,30,70,52,43,...,55,49,60,168,163,136,88,108,317,663
39,F83,De Punt,17,15,15,17,11,26,28,29,...,43,39,32,127,115,100,90,75,197,507

In [18]:
data.columns

Index(['code', 'city-part', '2015', '2016', '2017', '2018', '2019', '2015.1',
       '2016.1', '2017.1', '2018.1', '2019.1', '2015.2', '2016.2', '2017.2',
       '2018.2', '2019.2', '2015.3', '2016.3', '2017.3', '2018.3', '2019.3',
       '12-24', '25+'],
      dtype='object')

In [19]:

data2 = data[['code', 'city-part', '12-24', '25+']]

In [20]:
data_amsterdam_centrum = data2[data2.code == 'A']

In [21]:
data_amsterdam_centrum

  code                     city-part  12-24   25+
0    A         Burgwallen-Oude Zijde   2216  4953
1    A       Burgwallen-Nieuwe Zijde   4086  7519
2    A           Grachtengordel-West    231   565
3    A           Grachtengordel-Zuid   1543  2468
4    A            Nieuwmarkt/Lastage   1028  2613
5    A               Haarlemmerbuurt    353  1593
6    A                       Jordaan    530  1619
7    A             De Weteringschans   1480  2211
8    A         Weesperbuurt/Plantage    207   616
9    A  Oostelijke Eilanden/Kadijken    246   715

In [22]:
data_amsterdam_centrum['total'] = data_amsterdam_centrum['12-24']+data_amsterdam_centrum['25+']

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [23]:
data_amsterdam_centrum

  code                     city-part  12-24   25+  total
0    A         Burgwallen-Oude Zijde   2216  4953   7169
1    A       Burgwallen-Nieuwe Zijde   4086  7519  11605
2    A           Grachtengordel-West    231   565    796
3    A           Grachtengordel-Zuid   1543  2468   4011
4    A            Nieuwmarkt/Lastage   1028  2613   3641
5    A               Haarlemmerbuurt    353  1593   1946
6    A                       Jordaan    530  1619   2149
7    A             De Weteringschans   1480  2211   3691
8    A         Weesperbuurt/Plantage    207   616    823
9    A  Oostelijke Eilanden/Kadijken    246   715    961

In [24]:
#Here we calculate the total number of crimes. 
total_crime = data_amsterdam_centrum['total'].sum()
total_crime

36792

In [25]:
data_amsterdam_centrum['percentage'] = data_amsterdam_centrum['total']/total_crime*100

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [26]:
data_amsterdam_centrum

  code                     city-part  12-24   25+  total  percentage
0    A         Burgwallen-Oude Zijde   2216  4953   7169   19.485214
1    A       Burgwallen-Nieuwe Zijde   4086  7519  11605   31.542183
2    A           Grachtengordel-West    231   565    796    2.163514
3    A           Grachtengordel-Zuid   1543  2468   4011   10.901826
4    A            Nieuwmarkt/Lastage   1028  2613   3641    9.896173
5    A               Haarlemmerbuurt    353  1593   1946    5.289193
6    A                       Jordaan    530  1619   2149    5.840944
7    A             De Weteringschans   1480  2211   3691   10.032072
8    A         Weesperbuurt/Plantage    207   616    823    2.236899
9    A  Oostelijke Eilanden/Kadijken    246   715    961    2.611981

In [27]:
totale_misdrijven_onder_24 = total_crime - data_amsterdam_centrum['25+'].sum()
totale_misdrijven_onder_24
#Absolute cijfers 

#Percentage 
totale_misdrijven_onder_24_per = totale_misdrijven_onder_24/total_crime*100
#totale_misdrijven_onder_24_per

In [28]:
totale_misdrijven_boven_24 = total_crime - data_amsterdam_centrum['12-24'].sum()
totale_misdrijven_boven_24
#Absolute cijfers 

#Percentage 
totale_misdrijven_boven_24_per = totale_misdrijven_boven_24/total_crime*100
totale_misdrijven_boven_24_per

67.60165253315938

In [29]:
#We also wanna know in which street the most crimes happen:

data_streets = data_amsterdam_centrum.sort_values(by=['total'], ascending=False)
data_streets

  code                     city-part  12-24   25+  total  percentage
1    A       Burgwallen-Nieuwe Zijde   4086  7519  11605   31.542183
0    A         Burgwallen-Oude Zijde   2216  4953   7169   19.485214
3    A           Grachtengordel-Zuid   1543  2468   4011   10.901826
7    A             De Weteringschans   1480  2211   3691   10.032072
4    A            Nieuwmarkt/Lastage   1028  2613   3641    9.896173
6    A                       Jordaan    530  1619   2149    5.840944
5    A               Haarlemmerbuurt    353  1593   1946    5.289193
9    A  Oostelijke Eilanden/Kadijken    246   715    961    2.611981
8    A         Weesperbuurt/Plantage    207   616    823    2.236899
2    A           Grachtengordel-West    231   565    796    2.163514

In [30]:
#Here I check if the total crimes equals 100%
data_streets['percentage'].sum()

100.0

In [35]:
total_labels = ['Extreme Low', 'Low', 'Medium', 'High']

data_streets['labels_data'] = pd.cut(data_streets['total'], 4, labels=total_labels)
data_streets

,code,city-part,12-24,25+,total,percentage,labels_data
1,A,Burgwallen-Nieuwe Zijde,4086,7519,11605,31.542183,High
0,A,Burgwallen-Oude Zijde,2216,4953,7169,19.485214,Medium
3,A,Grachtengordel-Zuid,1543,2468,4011,10.901826,Low
7,A,De Weteringschans,1480,2211,3691,10.032072,Low
4,A,Nieuwmarkt/Lastage,1028,2613,3641,9.896173,Low
6,A,Jordaan,530,1619,2149,5.840944,Extreme Low
5,A,Haarlemmerbuurt,353,1593,1946,5.289193,Extreme Low
9,A,Oostelijke Eilanden/Kadijken,246,715,961,2.611981,Extreme Low
8,A,Weesperbuurt/Plantage,207,616,823,2.236899,Extreme Low
2,A,Grachtengordel-West,231,565,796,2.163514,Extreme Low

In [42]:
data_streets['each/day'] = (data_streets['total']/5/365).round(2)
data_streets

,code,city-part,12-24,25+,total,percentage,labels_data,each/day
1,A,Burgwallen-Nieuwe Zijde,4086,7519,11605,31.542183,High,6.36
0,A,Burgwallen-Oude Zijde,2216,4953,7169,19.485214,Medium,3.93
3,A,Grachtengordel-Zuid,1543,2468,4011,10.901826,Low,2.20
7,A,De Weteringschans,1480,2211,3691,10.032072,Low,2.02
4,A,Nieuwmarkt/Lastage,1028,2613,3641,9.896173,Low,2.00
6,A,Jordaan,530,1619,2149,5.840944,Extreme Low,1.18
5,A,Haarlemmerbuurt,353,1593,1946,5.289193,Extreme Low,1.07
9,A,Oostelijke Eilanden/Kadijken,246,715,961,2.611981,Extreme Low,0.53
8,A,Weesperbuurt/Plantage,207,616,823,2.236899,Extreme Low,0.45
2,A,Grachtengordel-West,231,565,796,2.163514,Extreme Low,0.44